### ISSUE TITLE
Test Flow Wifi Switch - Temperatur wird nicht abgefragt

### ISSUE THREAD

**Issue by DaWa74** [cgHome/homey.myStrom#10]
Hallo Chris
Ich bin mir nicht ganz sicher, ob ich mit dem Problem bei dir richtig bin.
Ich habe einen neuen Flow mit einem neuen Wifi Switch erstellt der aufgrund Temperaturänderung reagieren soll.
Beim Testen des Flows wird die Temperatur nicht abgefragt und der Test läuft leer durch. 
Spannenderweise funktioniert ein alter Flow mit einem anderen Wifi Switch weiterhin korrekt und fragt die Temperatur ab. 
wenn ich einen neuen Flow mit dem alten Wifi Switch erstelle, wird die Temperatur ebenfalls nicht abgefragt. 
Wo könnte das Problem liegen? App, Homey?
Die App habe ich bereits mal restartet
Gruss Dani

**Comment by cgHome** [comment]
Morgen,

Nur der neue Switch (v2) hat einen Temperaturfühler "onBoard", überprüfen kannst Du es folgend:

Via aktueller Firmware:
WiFi Switch v1 – Firmware 2.68
WiFi Switch v2 – Firmware 3.82

Oder mit der my.homey.app > Insights, dort wird die Temperatur angezeigt.

Wenn beides stimmt, dann hast Du ein Problem mit deinem Flow. Dann kannst Du dich vertrauensvoll an die Homey-Community wenden (https://community.athom.com/tag/flow)

Gruss

Chris

**Comment by DaWa74** [comment]
Hoi Chris
Besten Dank für die schnelle Antwort.
Es handelt sich um einen Switchmit Temperaturfühler.
Da ja der noch funktionierende alte Flow, beim Einbinden des gleichen alten Switch in einen neuen Flow auch nicht funktioniert, wird es wohl ein Problem von Homey sein.
Ich mach mich dann mal in der Community breit
Besten Dank
Gruss Dani

**Comment by cgHome** [comment]
Hallo, 

Der letzte Release ist jetzt 5 Monate alt und bis jetzt hat sich noch niemand beklagt, also nehme ich an, dass das Problem woanders liegen muss.

Aber ich bin gerne bereit, wenn Du mir den Flow zusenden kannst, das Problem genauer anzuschauen. Denn ich besitze keine Glaskugel und kann mit der Aussage, der Flow funktioniert nicht viel anfangen.

Gruss

**Comment by DaWa74** [comment]
Hallo Chris

Gerne, wenn du Zeit findest.
Nicht funktionierender Flow
https://homey.app/f/Ytpd-I




Das Problem liegt wirklich nur daran, dass der Test nicht mit Temperatureingabe gestartet wird. 
Es gibt bei den Bedingungen und Aktion auch kein Häkchen oder ein X
Es rödelt ein wenig auf dem Button Test und dann ist wieder fertig.
Der Flow selber funktioniert aber

Funktionierender Flow
https://homey.app/f/r5ph-I

Beim Start wird die Temperatur zur Eingabe abgefragt

Auch wenn ich nun den Wifi Switch Wohnwagen aus dem funktionierenden Flow nochmals in einen neuen Flow verwende, dann habe ich den gleichen Effekt und die Temperatur wird beim Test nicht abgefragt und Die Häkchen und Xen fehlen

Ein neuer ganz einfacher Flow, wenn heute Freitag und Sonne scheint, dann Message funktioniert inkl Markierung der Bedingungen/Aktionen

Herzlichen Dank
Gruss Dani

Von meinem iPad gesendet

**Comment by cgHome** [comment]
Falsch bei mir Funktioniert es, der Trigger wird gestartet !! 

Probier folgendes aus (ganz easy)

https://homey.app/de-ch/flow/Ytpd-I/

Mein SimpleLog:

2021-08-13 14:33:36 Temperatur changed to 23.6
2021-08-13 14:32:36 Temperatur changed to 23.5
2021-08-13 14:29:36 Temperatur changed to 23.6
2021-08-13 14:27:48 [Simple LOG] Cleared all logging data

**Comment by DaWa74** [comment]
Ok, schön zu hören
Von der url her müsste das mein Flow sein
Wolltest du mir was eigenes schicken?

Danke dass du dir die Zeit nimmst 

Von meinem iPhone gesendet

**Comment by cgHome** [comment]
Refresh Page !!

**Comment by DaWa74** [comment]
Ich sehe nur meinen Flow, auch wenn ich den Link im Laptop eingebe und vorher Cache gelöscht habe.
Vielleicht verstehe ich dich auch nicht richtig
Aber passt soweit.
Wenn ich über WebApp (Browser) einsteige, funktioniert das Testen, das Popup für die Temperatureingabe geht auf.
D.h die Homey-App hat ein kleines Problem.

Dann werde ich auf dem Laptop weitermachen

Herzlichen Dank für Deine promte Unterstützung
Grüsse aus Schaffhausen
Daniel

Von meinem iPad gesendet
