### ISSUE TITLE
Add WiFi Switch not possible

### ISSUE THREAD

**Issue by Morepower66** [cgHome/homey.myStrom#12]
Hi Chris

I can't add any devices in homey.
Failure: Es wurden keine neuen Geräte gefunden.

Versions:
Homey:
myStrom-SmartHome: v1.1.0
MyStrom Switches: v4.0
myStrom App IOS: newest version

Code: 4bdb1f9e-f269-446c-98b9-00a79998c5c4

Viele Grüsse
HP

**Comment by cgHome** [comment]
Sorry, but I'm in the middle of moving my apartment. My smart home is still in the boxes and unfortunately I can't do any testing at this time. I neither as soon as the system is up and running again, look at the problem.

Gruss Chris

**Comment by Morepower66** [comment]
No problem!

Sprichst Du deutsch?

Guten Umzug!

Viele Grüsse
HP

**Comment by cgHome** [comment]
Vielen Dank...

Das ist Neu !😕! Gemäss des Log meldet sich auch keiner. Warte einmal ein paar Minuten, eventuell hat der Discovery-Service seine liebe mühe.

Welche myStrom-Switch Version hast Du V1 oder V2 ?

**Comment by Morepower66** [comment]
Das ist eine gute Frage. Ich denke Version 1. Hier ein Foto der Etikette.

**Comment by Morepower66** [comment]
Hallo Chris

Ich nochmal:-)

Also ich hatte das Problem schon immer. Mit Shelly habe ich auch ab und zu Probleme. Aber da dauert es meistens 1-2 Tage und dann werden sie erkannt. myStrom WiFi-Switch habe ich von den 4 Stück noch nie einen gesehen. Sind aber aus der myStrom App problemlos erreichbar.

Viele Grüsse
HP

**Comment by cgHome** [comment]
Kann das Foto nicht sehen, sende mir doch ein Mail (cgHome@cFlat-inc.org) !!

**Comment by Morepower66** [comment]
Hi zusammen

Ging bei mir auch nie. Die myStrom-Dinger sind wirklich praktisch.
Ledvance wäre eine Alternative. Ich weiss aber nicht, ob die Schweizer Version in der Homey App unterstützt wird.

https://www.brack.ch/ledvance-smartplug-wifi-1250681?utm_source=google&utm_medium=cpc&utm_campaign=%21cc-pssh%21l-d%21e-g%21t-pla%21k1-bh%21z-baumarkt_hobby_hm_pmax&utm_term=&adgroup_id=&ad_type=pla&prod_id=1250681&campaign_id=18012302858&SEMscout&gclid=Cj0KCQjwpeaYBhDXARIsAEzItbGadgkyzkg3IFH_Eilt1wh-Wk3REBsuzHN88kq3Z7ibhps3IWAV3ZQaArxKEALw_wcB&hc_fcv=YxojxAKYlYxjQbDE~MlcXl1A1Bb9-Vk-kzzzzzzzz~MEqQXhE1QwevL-6Hzzzzzzzz￼


Viele Grüss
HP

**Comment by cgHome** [comment]
Morgen,

Das Problem ist in Bearbeitung [siehe](https://community.homey.app/t/app-pro-mystrom-smart-home-app-for-homey-v1-0-10/12507/32)

Gruss Chris
