### ISSUE TITLE
Probleme beim Hinzufügen von myStrom Switch

### ISSUE THREAD

**Issue by mas12021979** [cgHome/homey.myStrom#16]
Hallo, 

ich habe gestern über die Homey App einen Diagnostik File zugesendet. Darauf kam dann die Rückfrage ob Version 1 oder 2. 

Wo kann ich das sehen? Der Switch wurde jetzt vor 2 Wochen bei Amazon erworben. Ich denke also es ist die Neueste Version. Firmware ist laut App 4.0.4

Bei dem Versiuch des Hinzufügens sieht man im Prozess ein kurzes Zwischenbild und dann spring das direkt um auf "Es wurden keine Geräte gefunden". Siehe Video.

Danke vorab für die Unterstützung!

VG!
Markus

https://user-images.githubusercontent.com/119403062/204759512-a88661e6-ab8e-4b83-92e2-ff3712d35769.mov

**Comment by cgHome** [comment]
Morgen,

Das sagt mir eben nichts. Schick mir bitte ein Bild der Vor- und Rückseite des Switch..

Gruss

**Comment by mas12021979** [comment]
Mache ich wenn ich heute zuhause bin! Danke vorab!

**Comment by mas12021979** [comment]
Hier nun die Fotos des Gerätes.

VG!
Markus
![IMG_7594](https://user-images.githubusercontent.com/119403062/204848076-a261b182-d2fa-4f03-a03c-ebee99440f81.jpeg)
![IMG_7595](https://user-images.githubusercontent.com/119403062/204848093-ca656f5b-9dba-46c9-93f8-b228b9ec995f.jpeg)
![IMG_7596](https://user-images.githubusercontent.com/119403062/204848098-cdc8f3fa-d7a7-4e0c-a420-7c1f784cdcca.jpeg)

**Comment by cgHome** [comment]
Ich habe mich nochmals schlau gemacht. 

Theoretisch (gemäss Doku) sollte es funktionieren, aber testen kann ich es nicht, weil ich nur CH-Stecker besitze und aus diesem Grund die EU-Stecker nur "bedingt" unterstütz kann. Es ist mir auch niemand bekannt der EU-Stecker im Einsatz hat.

Falls der Switch im Pairing nicht auftaucht, dann könnte es ein "udp port" Problem sein, für dies bitte ich dich, dich in der [Community](https://community.homey.app/t/app-pro-mystrom-smart-home/12507) schlau zu machen.

Sorry Chris

**Comment by cgHome** [comment]
Sali Markus,

Ich habe auf [Test](https://homey.app/a/ch.mystrom.smarthome/test/), eine neue Version der myStrom-App gestellt, sie wurde leider noch nicht von athom auf live gestellt. Neben anderen Fehler, habe ich noch ein Zahlendreher beim Switch EU gefunden (Sorry), versuches doch nochmals eventuell funktioniert es...

BDW: Ob es ein "udp" Problem ist oder nicht, findest Du jetzt neu, in der Timeline der myStrom-App heraus. Denn alle gefunden Devices werden einmal ausgegeben. Vielleicht hilft Dir das weiter...

Gruss Chris
