### ISSUE TITLE
Problems with registering

### ISSUE THREAD

**Issue by Caflino** [cgHome/homey.myStrom#2]
Hi! I just bought a homey and tried to register my devices to it. The Switches worked as expected. The problems are my Bulb, Wifi Button and Wifi Button plus. I can't register either of those. I made myself a new mystrom Account and registered all devices new. Could you please help me with my problem? :)

**Comment by josefzahner** [comment]
Hi, I'm using a Button+, have you tried this:
"Button+: Open the back of the button by rotating it clockwise. Remove the batteries and reinsert them. The Button+ should now be visible."

**Comment by srietveld** [comment]
Same with me. i try to register my two mystrom bulbs buy the app is niet able to find either. Is there a sollution?

**Comment by cgHome** [comment]
[see README.md](https://github.com/cgHome/homey.myStrom/blob/main/README.md)

**Keep in mind that in order for the Button or Button+ to respond to any of these requests they have to be in the configuration mode:**

- Button: (Re-)Connect the button to a power source with the provided USB cable. Press the button and after some time it should become visible in the network.

- Button+: Open the back of the button by rotating it clockwise. Remove the batteries and reinsert them. The Button+ should now be visible.
