### ISSUE TITLE
Error with Smart Switches

### ISSUE THREAD

**Issue by Dabu82** [cgHome/homey.myStrom#3]
Hi Chris
I have a Problem since several months with my WiFi Switches.
Almost every 2 days my Switches going offline and a exclamation mark appears
with the response error: ECONNREFUSED.

Then i have to delete the switches, restart the app and add them agian.
The switches works without any problems with the original myStrom-App.

My diagnoses report: 
dbea82a7-c9ce-49a0-b12a-38a2cdbf2310

Thank you
Michael

**Comment by cgHome** [comment]
Is the firmware up to date?

**Comment by DaWa74** [comment]
Hoi Chris
Ich habe ein ähnliches Problem 
Wenn ich den Router neu starte, dann sind ein paar meiner Switches nicht mehr erreichbar und ich muss die jeweils neu hinzufügen. Da die myStrom App mich zur Zeit nicht in die Einstellungen lässt, kann ich nicht überprüfen ob es ältere oder neuere Switches sind
Hast du ev. Eine Erklärung?
Danke
Gruss Dani

**Comment by cgHome** [comment]
Morgen Dani,

Du kannst einfach feststellen ob der Switch V1 oder V2 ist. Du musst nur kontrollieren, ob er eine Temperatur ungleich 0 anzeigt, wenn ja dann ist es ein V2 Modell ..😀..

Zum Problem mit dem Restart des Routers, eventuell funktioniert der Discovery-Service deines Router nicht richtig. Als Workaround weise den myStrom-Switches doch eine fixe IP-Adresse zu (ist so oder so besser), dann sollten sie nach einem Restart immer noch funktionieren...

Gruss Chris

**Comment by DaWa74** [comment]
Hoi Chris
Herzlichen Dank für deine schnelle Antwort 
Ich werde es mit der festen IP mal versuchen
Gruss Dani

Von meinem iPhone gesendet
