### ISSUE TITLE
Unable to add plugs after reinstalling app

### ISSUE THREAD

**Issue by theduqueduque** [cgHome/homey.myStrom#5]
Hello There

I had 3 plugs added in homey for a long time and always worked perfectly.
I bought 6new plugs Andries to add them all new to honey, which worked to add them but only 1 wasshowingasconnected.the others where all offline.
Now 8 reinstalled the app and try to add the plugs again but always get a timeout and homey cannot find any plugs
717c18fd-5843-4748-9da1-3a747b027307
Here is the diagnostic code

Thank your your help.

**Comment by cgHome** [comment]
Guten Morgen,

First try to unplug and plug in the device, then you have about 5 minutes to pair the device with the homey. myStrom devices are only in pair mode for a short time.

btw, the diagnostic code is unfortunately only for athom itself, I have no access to it.

Gruss Chris

**Comment by theduqueduque** [comment]
Hallo Chris

Also verstehe ich es richtig.
Die myStrom Plugs werden somit von Homey nicht über irgendeine API zum 
myStrom Portal oder sonst wie gefunden. Sondern die Plugs müssen beim 
"starten" mit Homey verbunden werden.
Gut zu wissen. Wobei als ich die Adapter für einmal hinzufügen konnte 
waren seit der ersten Inbetriebnahme der Plugs schon einige Stunden 
vergangen. Dennoch hat Homey alle 9 gesehen, aber wie gesagt. Es war nur 
einer davon erreichbar von Homey.

Ich werde das heute Abend mal versuchen.
Der eine Plug wo die ganze IT dran hängt könnte aber ein Problem werden 
;)
Kann man die Plugs "neustarten" ohne aus/einstecken?

Danke & Gruss
Alex

Am 02.10.2020 07:29, schrieb Chris Gross:

**Comment by theduqueduque** [comment]
Hallo Chris

Leider hat das nicht den gewünschten Effekt gebracht.
Habe 3 der Plus mal aus/eingesteckt und gewartet bis die LED weiss ist.
Aber mit Homey finde ich nun keine Plugs mehr.
Hast du noch eine weitere Idee woran es liegen könnte?

Danke & Gruss
Alex

Am 02.10.2020 07:29, schrieb Chris Gross:

**Comment by cgHome** [comment]
Morning,

i cannot reproduce the problem, i suggest the following

- Test the plugs are visible via the myStrom app (IOS/Android) and is the FW accurate. If no > Configure in app and update FW.
- Test the plug's with the myStrom app.
- Have you defined any log-flows ? (Error comes from this corner) If yes, delete them.
- If everything doesn't help, uninstall Homey myStrom app and reinstall everything.

PS: You are the only one with these problems, so there must be something special about your system. 

Gruss
Chris

**Comment by theduqueduque** [comment]
Hello Chris

Does it have something todo with Homey v5.0 i have installed?
I read it uses SDK3.0 and not 1.0 anymore (I think). I had the update 
message and well just clicked update without realising its still a Beta.

How does your Homey App find the Plugs?

Will try your suggestions and let you know if it helped.
Thank you and best regards
Alex

Am 05.10.2020 08:27, schrieb Chris Gross:

**Comment by cgHome** [comment]
SORRY, nobody said anything about the app working under Homey v5. 

**Homey v5 is still beta and beta versions are not suported**
