### ISSUE TITLE
Request/Question

### ISSUE THREAD

**Issue by theduqueduque** [cgHome/homey.myStrom#7]
Hello There

I tried the Power by the Hour app from the Homey store and it shows the Fibaro Devices but not the MyStrom Adapter. I asked the developer if they can be integrated or what might be the reason for them not showing up. 
The developer told me the following:
"Any app that has a meter_power capability should appear when trying to pair. Ask the developer if he has this capability."

So I am not familiar with that topic, but I thought I post the question here and hopefully it is possible to add that "flag/option" to the app.

Thank you again for providing this great app to the Homey world
Best Regards
Duque

**Comment by cgHome** [comment]
[A measure_power capability is defined](https://github.com/cgHome/homey.myStrom/blob/230a345d8cedc8cf122f2b8dd40e87d83193a419/app.json#L42)

Chris
